-- A
#CREATE EXTENSION IF NOT EXISTS "pgcrypto";


CREATE TABLE IF NOT EXISTS joueurs (
  id_joueur UUID PRIMARY KEY,
  nom TEXT UNIQUE NOT NULL,
  date_creation TIMESTAMP DEFAULT NOW(),
  is_human BOOLEAN DEFAULT TRUE

);

